# .github/configs/label-commenter-config.yml

labels:
  - name: 'active'
    labeled:
      issue:
        body: |
          **🎉 您的友链已通过是非题的审核并添加！**
          
          **🖖 博主您好，还请多多关照**

          您可以前往 [https://www.shifeiti.com/friends/](https://www.shifeiti.com/friends/) 看到您的网站。

          > 如果您的站点信息发生了变动，请直接修改这个 [issue](https://github.com/i-abc/blog-friends/issues) 的内容。

  - name: 'suspend'
    labeled:
      issue:
        body: |
          **👋 请及时添加本站友链**
          
          **❤ 博主您好，经拜访发现你还未添加本站友链，请及时添加**

          距离成功只剩一步之遥了，请把本站添加到您的友链中，然后再下方评论告知。

  - name: '404'
    labeled:
      issue:
        body: |
          **⚠️ 抱歉，您的网站打不开，现已下架。**
          
          **😢 请问是遇见什么困难了吗，若能帮忙，在所不辞**

          如果您确认可以打开，请在下方评论告知，我们会在人工审核通过后恢复上架。
